import Head from 'next/head'
import axios from 'axios'
import { NextPage } from 'next'
import { Video } from 'types'
import VideoCard from '@/components/VideoCard'
import NoResults from '@/components/NoResults'
import { BASE_URL } from '@/utils'

// here interface is an object explaining how is our obj will look like by specifying its type
// specifying type is power of typescript so we dont have to guess but know exactly what we are working with
interface Iprops{
  videos:Video[]
}

const Home=({videos}:Iprops)=> {
  console.log(videos)
  return (
    <>
      <Head>
        <title>CareFree</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex flex-col gap-10 videos h-full'>
      {videos.length 
        ? videos?.map((video: Video) => (
          <VideoCard post={video} key={video._id} />
        )) 
        : <NoResults text={`No Videos`} />}
    </div>




      
    </>
  )
}

// to fetch data in next js use getServerSideProps and see nextjs documentation when to use it

// look at the website in browser it is localhost:3000/?topic=${item.name}
// here /?topic=${item.name} is a query of router and we can easily use it it our get server side as parameter
// {query:{topic}

export const getServerSideProps = async ({query:{topic}}:{query:{topic:string}})=> {
  // inside nextjs we can make own fullfetch backend server in api folder
  // next js file based routing system : file based repuest example in url /api/post is same as file structure in in our page folder
  // destructuring data out of api
  let response=await axios.get(`${BASE_URL}/api/post`);

  
  if(topic) {
    response = await axios.get(`${BASE_URL}/api/discover/${topic}`);
  }

  // console.log(response.data.name)
  

  // we also need return statement
  
  return{
    // in nextjs getserverSideProps whatever we put in props below will automaticall be populated inside real props on Home page above 
    props:{
      videos:response.data
    }
  }
  
}

export default  Home